tankathon_bballgm_team_mapper = {
    "Utah": "Utah Jazz",
    "Washington": "Washington Wizards",
    "Charlotte": "Charlotte Hornets",
    "New Orleans": "New Orleans Pelicans",
    "Brooklyn": "Brooklyn Nets",
    "Philadelphia": "Philadelphia 76ers",
    "Toronto": "Toronto Raptors",
    "San Antonio": "San Antonio Spurs",
    "Portland": "Portland Trail Blazers",
    "Miami": "Miami Heat",
    "Chicago": "Chicago Bulls",
    "Phoenix": "Phoenix Suns",
    "Dallas": "Dallas Mavericks",
    "Sacramento": "Sacramento Kings",
    "Orlando": "Orlando Magic",
    "Atlanta": "Atlanta Hawks",
    "Milwaukee": "Milwaukee Bucks",
    "Minnesota": "Minnesota Timberwolves",
    "Detroit": "Detroit Pistons",
    "Golden State": "Golden State Warriors",
    "LA Clippers": "Los Angeles Clippers",
    "Indiana": "Indiana Pacers",
    "LA Lakers": "Los Angeles Lakers",
    "Memphis": "Memphis Grizzlies",
    "Denver": "Denver Nuggets",
    "New York": "New York Knicks",
    "Houston": "Houston Rockets",
    "Boston": "Boston Celtics",
    "Cleveland": "Cleveland Cavaliers",
    "Oklahoma City": "Oklahoma City Thunder",
}

team_abbr = {
    "Utah Jazz": "UTA",
    "Washington Wizards": "WAS",
    "Charlotte Hornets": "CHA",
    "New Orleans Pelicans": "NOP",
    "Brooklyn Nets": "BKN",
    "Philadelphia 76ers": "PHI",
    "Toronto Raptors": "TOR",
    "San Antonio Spurs": "SAS",
    "Portland Trail Blazers": "POR",
    "Miami Heat": "MIA",
    "Chicago Bulls": "CHI",
    "Phoenix Suns": "PHX",
    "Dallas Mavericks": "DAL",
    "Sacramento Kings": "SAC",
    "Orlando Magic": "ORL",
    "Atlanta Hawks": "ATL",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW",
    "Los Angeles Clippers": "LAC",
    "Indiana Pacers": "IND",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Denver Nuggets": "DEN",
    "New York Knicks": "NYK",
    "Houston Rockets": "HOU",
}
