tankathon_bballgm_team_mapper = {
    "Utah": "Utah Jazz",
    "Washington": "Washington Wizards",
    "Charlotte": "Charlotte Hornets",
    "New Orleans": "New Orleans Pelicans",
    "Brooklyn": "Brooklyn Nets",
    "Philadelphia": "Philadelphia 76ers",
    "Toronto": "Toronto Raptors",
    "San Antonio": "San Antonio Spurs",
    "Portland": "Portland Trail Blazers",
    "Miami": "Miami Heat",
    "Chicago": "Chicago Bulls",
    "Phoenix": "Phoenix Suns",
    "Dallas": "Dallas Mavericks",
    "Sacramento": "Sacramento Kings",
    "Orlando": "Orlando Magic",
    "Atlanta": "Atlanta Hawks",
    "Milwaukee": "Milwaukee Bucks",
    "Minnesota": "Minnesota Timberwolves",
    "Detroit": "Detroit Pistons",
    "Golden State": "Golden State Warriors",
    "LA Clippers": "Los Angeles Clippers",
    "Indiana": "Indiana Pacers",
    "LA Lakers": "Los Angeles Lakers",
    "Memphis": "Memphis Grizzlies",
    "Denver": "Denver Nuggets",
    "New York": "New York Knicks",
    "Houston": "Houston Rockets",
    "Boston": "Boston Celtics",
    "Cleveland": "Cleveland Cavaliers",
    "Oklahoma City": "Oklahoma City Thunder",
}
